### ISSUE TITLE
`BaseSerializable.__eq__` bug

### ISSUE THREAD

**Issue by hwwhww** [ethereum/py-ssz#62]
## What was wrong?

The current `BaseSerializable.__eq__` overwritten:

https://github.com/ethereum/py-ssz/blob/91f0928cd8fb8b8f3f67fc6799a31f14daf98b30/ssz/sedes/serializable.py#L137-L138

I found it's incorrect when I do the `==` assertion with `SignedSerializable` object, where `SignedSerializable`  inherits `BaseSerializable`, not `Serializable`:

https://github.com/ethereum/py-ssz/blob/91f0928cd8fb8b8f3f67fc6799a31f14daf98b30/ssz/sedes/signed_serializable.py#L65-L68

## How can it be fixed?
1. Fix `BaseSerializable.__eq__`: change `isinstance(other, Serializable)` to `isinstance(other, BaseSerializable)`
2. Question: should `SignedSerializable`  inherits `Serializable` instead of `BaseSerializable`?
3. Question: use `root` (`hash_tree_root`) instead of bulti-in `hash`? 
https://github.com/ethereum/py-ssz/blob/91f0928cd8fb8b8f3f67fc6799a31f14daf98b30/ssz/sedes/serializable.py#L140-L155

**Comment by jannikluhn** [comment]
> Fix `BaseSerializable.__eq__`: change `isinstance(other, Serializable)` to `isinstance(other, BaseSerializable)`

:+1:


> Question: should SignedSerializable inherits Serializable instead of BaseSerializable?

To be honest I don't really see a good reason why we've got `BaseSerializable` at all, instead of just putting everything in `Serializable` directly. The only difference is that `Serializable` has `MetaSerializable` as a metaclass, but `BaseSerializable` has not. `BaseSerializable` isn't really usable without the metaclass though.

The reason why I chose `BaseSerializable` as parent for `SignedSerializable` is that it uses a different metaclass than `Serializable`. But I quickly tested it and replacing metaclasses in subclasses seems to work fine, so it was not a good reason. So I'm fine with both options.

>  Question: use root (hash_tree_root) instead of bulti-in hash?

:+1: for both `__eq__` and `__hash__`. The linked Python docs say the following which presumably is the reason why we're using the built-in hash functions:

```
This is intended to provide protection against a denial-of-service caused by carefully-chosen inputs that exploit the worst case performance of a dict insertion, O(n^2) complexity.
```

But I think this doesn't apply to us because one can't "carefully choose" the hash of SSZ objects.
